image: registry.gitlab.yum.com/yum-shared/docker-images/node:14

stages:
  - publish

publish:
  stage: publish
  rules:
    - if: "$CI_COMMIT_TAG"
      when: on_success
  script:
    - npm install -g npm
    - mv .npmrc-gitlab-dependencies .npmrc
    - npm i
    - npm publish
